headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "Referer": "https://www.net-empregos.com/",
    "Origin": "https://www.net-empregos.com",
    "Connection": "keep-alive"
}

NET_EMPREGOS_DISTRICTS = {
    "acores": "25",
    "aveiro": "4",
    "beja": "15",
    "braga": "3",
    "bragança": "5",
    "braganca": "5",
    "castelo branco": "10",
    "coimbra": "9",
    "evora": "14",
    "faro": "17",
    "guarda": "7",
    "leiria": "11",
    "lisboa": "1",
    "madeira": "26",
    "portalegre": "16",
    "porto": "2",
    "santarem": "12",
    "setubal": "13",
    "viana do castelo": "28",
    "vila real": "6",
    "viseu": "8",
    "angola": "20",
    "brasil": "18",
    "cabo verde": "24",
    "guine bissau": "22",
    "mocambique": "21",
    "sao tome e principe": "23",
    "timor": "27",
    "estrangeiro": "29"
}

NET_EMPREGOS_CATEGORIES = {
    "administracao / secretariado": "29", "administracao": "29", "secretariado": "29",
    "agricultura / florestas / pescas": "39", "agricultura": "39", "florestas": "39", "pescas": "39",
    "arquitectura / design": "22", "arquitectura": "22", "design": "22",
    "artes / entretenimento / media": "40", "artes": "40", "entretenimento": "40",
    "banca / seguros / servicos financeiros": "16", "banca": "16", "seguros": "16", "financas": "15",
    "beleza / moda / bem estar": "47", "beleza": "47", "moda": "47", "bem estar": "47",
    "call center / help desk": "57", "call center": "57", "help desk": "57",
    "comercial / vendas": "53", "comercial": "53", "vendas": "53",
    "comunicacao social / media": "8", "comunicacao social": "8",
    "conservacao / manutencao / tecnica": "51", "conservacao": "51", "manutencao": "51",
    "construcao civil": "23",
    "contabilidade / financas": "15", "contabilidade": "15",
    "desporto / ginasios": "28", "desporto": "28", "ginasios": "28",
    "direito / justica": "44", "direito": "44", "justica": "44",
    "educacao / formacao": "11", "educacao": "11", "formacao": "11",
    "engenharia ( ambiente )": "54", "engenharia ambiente": "54",
    "engenharia ( civil )": "45", "engenharia civil": "45",
    "engenharia ( eletrotecnica )": "46", "engenharia eletrotecnica": "46",
    "engenharia ( mecanica )": "24", "engenharia mecanica": "24",
    "engenharia ( quimica / biologia )": "50", "engenharia quimica": "50", "engenharia biologia": "50",
    "farmacia / biotecnologia": "41", "farmacia": "41", "biotecnologia": "41",
    "gestao de empresas / economy": "26", "gestao de empresas": "26", "economia": "26",
    "gestao rh": "32", "rh": "32", "recursos humanos": "32",
    "hotelaria / turismo": "9", "hotelaria": "9", "turismo": "9",
    "imobiliario": "12",
    "industria / producao": "6", "industria": "6", "producao": "6",
    "informatica ( analise de sistemas )": "38", "analise de sistemas": "38",
    "informatica ( formacao )": "34",
    "informatica ( gestao de redes )": "37", "gestao de redes": "37",
    "informatica ( internet )": "35", "internet": "35",
    "informatica ( multimedia )": "36", "multimedia": "36",
    "informatica ( programacao )": "5", "programacao": "5", "informatica": "5",
    "informatica ( tecnico de hardware )": "49", "hardware": "49",
    "informatica (comercial/gestor de conta)": "56",
    "limpezas / domesticas": "58", "limpezas": "58",
    "lojas / comercio / balcao": "30", "lojas": "30", "comercio": "30", "balcao": "30",
    "publicidade / marketing": "19", "publicidade": "19", "marketing": "19",
    "relacoes publicas": "18",
    "restauracao / bares / pastelarias": "42", "restauracao": "42", "bares": "42",
    "saude / medicina / enfermagem": "14", "saude": "14", "medicina": "14", "enfermagem": "14",
    "servicos sociais": "55",
    "servicos tecnicos": "52",
    "telecomunicacoes": "1",
    "transportes / logistica": "43", "transportes": "43", "logistica": "43"
}