HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "Referer": "https://emprego.sapo.pt/",
    "Origin": "https://emprego.sapo.pt",
    "Connection": "keep-alive",
}

BASE_URL = "https://emprego.sapo.pt"

DISTRICT_SLUGS: dict[str, str] = {
    "aveiro": "aveiro",
    "beja": "beja",
    "braga": "braga",
    "braganca": "braganca",
    "bragança": "braganca",
    "castelo branco": "castelo-branco",
    "coimbra": "coimbra",
    "evora": "evora",
    "évora": "evora",
    "faro": "faro",
    "guarda": "guarda",
    "leiria": "leiria",
    "lisboa": "lisboa",
    "lisbon": "lisboa",
    "portalegre": "portalegre",
    "porto": "porto",
    "santarem": "santarem",
    "santarém": "santarem",
    "setubal": "setubal",
    "setúbal": "setubal",
    "viana do castelo": "viana-do-castelo",
    "vila real": "vila-real",
    "viseu": "viseu",
    "madeira": "ilha-da-madeira",
    "porto santo": "ilha-de-porto-santo",
    "santa maria": "ilha-de-santa-maria",
    "sao jorge": "ilha-de-sao-jorge",
    "são jorge": "ilha-de-sao-jorge",
    "sao miguel": "ilha-de-sao-miguel",
    "são miguel": "ilha-de-sao-miguel",
    "corvo": "ilha-do-corvo",
    "faial": "ilha-do-faial",
    "pico": "ilha-do-pico",
    "graciosa": "ilha-graciosa",
    "terceira": "ilha-terceira",
    "flores": "ilha-das-flores",
    "internacional": "Internacional",
    "international": "Internacional",
}

CATEGORY_SLUGS: dict[str, str] = {
    "administrativo": "administrativo-secretariado",
    "administrativo / secretariado": "administrativo-secretariado",
    "administrativo-secretariado": "administrativo-secretariado",
    "agricultura": "agricultura-pescas",
    "agricultura / pescas": "agricultura-pescas",
    "agricultura-pescas": "agricultura-pescas",
    "ambiente": "ambiente",
    "arquitetura": "arquitetura",
    "automovel": "automovel",
    "banca": "banca-seguros",
    "banca / seguros": "banca-seguros",
    "banca-seguros": "banca-seguros",
    "beleza": "beleza-estetica-bem-estar",
    "beleza-estetica-bem-estar": "beleza-estetica-bem-estar",
    "call-center": "call-center-helpdesk-telemarketing",
    "call-center-helpdesk-telemarketing": "call-center-helpdesk-telemarketing",
    "comercial": "comercial-vendas",
    "comercial / vendas": "comercial-vendas",
    "comercial-vendas": "comercial-vendas",
    "comunicacao": "comunicacao-media-redes-sociais",
    "comunicacao-media-redes-sociais": "comunicacao-media-redes-sociais",
    "construcao": "construcao-civil",
    "construcao-civil": "construcao-civil",
    "consultadoria": "consultadoria-auditoria-assessoria",
    "consultadoria-auditoria-assessoria": "consultadoria-auditoria-assessoria",
    "contabilidade": "contabilidade-fiscalidade-financas",
    "contabilidade-fiscalidade-financas": "contabilidade-fiscalidade-financas",
    "design": "design-multimedia-artes-graficas",
    "design-multimedia-artes-graficas": "design-multimedia-artes-graficas",
    "desporto": "desporto-fitness",
    "desporto-fitness": "desporto-fitness",
    "engenharia": "engenharia",
    "formacao": "formacao-ensino-educacao",
    "formacao-ensino-educacao": "formacao-ensino-educacao",
    "gestao": "gestao-economia",
    "gestao-economia": "gestao-economia",
    "grande-consumo": "grande-consumo-retail",
    "grande-consumo-retail": "grande-consumo-retail",
    "hotelaria": "hotelaria-restauracao-turismo",
    "hotelaria-restauracao-turismo": "hotelaria-restauracao-turismo",
    "imobiliario": "imobiliario",
    "industria": "industria-manutencao",
    "industria-manutencao": "industria-manutencao",
    "informatica": "informatica-tecnologias",
    "informatica-tecnologias": "informatica-tecnologias",
    "juridico": "juridico",
    "limpezas": "apoio-domiciliario-e-limpezas",
    "apoio-domiciliario-e-limpezas": "apoio-domiciliario-e-limpezas",
    "linguas": "linguas-traducao",
    "linguas-traducao": "linguas-traducao",
    "logistica": "logistica-compras-distribuicao",
    "logistica-compras-distribuicao": "logistica-compras-distribuicao",
    "marketing": "marketing-publicidade-rp",
    "marketing-publicidade-rp": "marketing-publicidade-rp",
    "moda": "moda-confeccao-textil",
    "moda-confeccao-textil": "moda-confeccao-textil",
    "proprio-emprego": "proprio-emprego",
    "qualidade": "qualidade",
    "recursos-humanos": "recursos-humanos",
    "saude": "saude",
    "seguranca": "seguranca",
}